# HPC in Bioinformatics: How does it help?

```{r, echo = FALSE, results='asis'}
knitr::opts_chunk$set(echo = FALSE)

# Uncomment to change widget colours:
#style_widgets(incorrect = "goldenrod", correct = "purple", highlight = "firebrick")
```

## Watch the video

The second video explains the main components of a high performance computer cluster.

{{< video https://www.youtube.com/embed/dV6mM-GJeII?si=Q6X8HtYdnR9XhZsf >}}

## Test your knowledge

After watching the video, check your knowledge by answering the following questions.

::: {.webex-check .webex-box}
```{r, results='asis'}
# QUESTION 1
opts1 <- c(
   "importance of jobs",
   answer = "first come first serve",
   "number of resources requested"
)
cat("How is the queue managed?", longmcq(opts1))

# QUESTION 2
opts1 <- c(
   answer = "use of multiple cpu",
   "reservation of RAM",
   "submitting multiple jobs"
)
cat("What is parallelism or multi-threading?", longmcq(opts1))

# QUESTION 3
opts1 <- c(
   "125-fold",
   "3-fold",
   answer = "15-fold"
)
cat("If you take 5 files, and run a job using 3 cpus per file, how much are you decreasing the time it takes for your job to run?", longmcq(opts1))

```
:::
